services:
  web:
    build:
      context: .
      args:
        - OPENAI_API_KEY=$OPENAI_API_KEY
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./certs:/tmp/certs:ro
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - redis
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  redis:
    image: "redis:alpine"
    env_file:
      - .env
    command: --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
